---
sudo: required
language: python
services:
  - docker

stages:
  - linter
  - test

env:
  global:
    - image=debian version=8
    - image=debian version=9
    - image=centos version=7
  matrix:
    - group=memfile
    - group=mysql


matrix:
  fast_finish: true

jobs:
  include:
    - name: deploy kea on $image $version with $group as backends
      script:
        - >
           travis_wait 45 sleep infinity & docker run --rm -it
           --mount type=bind,source="$(pwd)",target=/tmp/$(basename "$PWD")
           -v /var/run/docker.sock:/var/run/docker.sock
           -w /tmp/$(basename "$PWD")
           quay.io/ansible/molecule:latest
           sudo molecule test
    - stage: linter
      env: image=debian verion=9 group=memfile
      script:
        - >
           docker run --rm -it
           --mount type=bind,source="$(pwd)",target=/tmp/$(basename "$PWD")
           -v /var/run/docker.sock:/var/run/docker.sock
           -w /tmp/$(basename "$PWD")
           quay.io/ansible/molecule:latest
           sudo molecule lint

notifications:
  email:
    on_failure: change
    on_success: never
