---
sudo: required
language: python
services:
  - docker

stages:
  - linter
  - deploy

matrix:
  fast_finish: true

jobs:
  include:
    - stage: linter
      script:
        - >
           docker run --rm -it
           --mount type=bind,source="$(pwd)",target=/tmp/$(basename "$PWD")
           -v /var/run/docker.sock:/var/run/docker.sock
           -w /tmp/$(basename "$PWD")
           quay.io/ansible/molecule:latest
           sudo molecule lint
    - stage: deploy
      name: deploy kea
      env:
        - scenario=deploy-debian-7
        - scenario=deploy-debian-8
        - scenario=deploy-debian-9
        - scenario=deploy-centos-7
      script:
        - >
           travis_wait 30 sleep infinity & docker run --rm -it
           --mount type=bind,source="$(pwd)",target=/tmp/$(basename "$PWD")
           -v /var/run/docker.sock:/var/run/docker.sock
           -w /tmp/$(basename "$PWD")
           quay.io/ansible/molecule:latest
           sudo molecule test --scenario-name $scenario
    - stage: deploy
      name: deploy kea on debian 7
      env:
        - scenario=deploy-debian-7
      script:
        - >
           travis_wait 30 sleep infinity & docker run --rm -it
           --mount type=bind,source="$(pwd)",target=/tmp/$(basename "$PWD")
           -v /var/run/docker.sock:/var/run/docker.sock
           -w /tmp/$(basename "$PWD")
           quay.io/ansible/molecule:latest
           sudo molecule test --scenario-name $scenario
    - stage: deploy
      name: deploy kea on debian 8
      env:
        - scenario=deploy-debian-8
      script:
        - >
           travis_wait 30 sleep infinity & docker run --rm -it
           --mount type=bind,source="$(pwd)",target=/tmp/$(basename "$PWD")
           -v /var/run/docker.sock:/var/run/docker.sock
           -w /tmp/$(basename "$PWD")
           quay.io/ansible/molecule:latest
           sudo molecule test --scenario-name $scenario
    - stage: deploy
      name: deploy kea on debian 9
      env:
        - scenario=deploy-debian-9
      script:
        - >
           travis_wait 30 sleep infinity & docker run --rm -it
           --mount type=bind,source="$(pwd)",target=/tmp/$(basename "$PWD")
           -v /var/run/docker.sock:/var/run/docker.sock
           -w /tmp/$(basename "$PWD")
           quay.io/ansible/molecule:latest
           sudo molecule test --scenario-name $scenario
    - stage: deploy
      name: deploy kea on centos 7
      env:
        - scenario=deploy-centos-7
      script:
        - >
           travis_wait 30 sleep infinity & docker run --rm -it
           --mount type=bind,source="$(pwd)",target=/tmp/$(basename "$PWD")
           -v /var/run/docker.sock:/var/run/docker.sock
           -w /tmp/$(basename "$PWD")
           quay.io/ansible/molecule:latest
           sudo molecule test --scenario-name $scenario

notifications:
  email:
    on_failure: change
    on_success: never
