---
sudo: required
language: python
services:
  - docker

stages:
  - linter
  - deploy

matrix:
  fast_finish: true

jobs:
  include:
    - stage: linter
      script:
        - >
           docker run --rm -it
           --mount type=bind,source="$(pwd)",target=/tmp/$(basename "$PWD")
           -v /var/run/docker.sock:/var/run/docker.sock
           -w /tmp/$(basename "$PWD")
           quay.io/ansible/molecule:latest
           sudo molecule lint
    - stage: deploy
      name: deploy kea whith memfile as backends
      env:
        - scenario=deploy-kea-memfile
      script:
        - >
           travis_wait 45 sleep infinity & docker run --rm -it
           --mount type=bind,source="$(pwd)",target=/tmp/$(basename "$PWD")
           -v /var/run/docker.sock:/var/run/docker.sock
           -w /tmp/$(basename "$PWD")
           quay.io/ansible/molecule:latest
           sudo molecule test --scenario-name $scenario
    - stage: deploy
      name: deploy kea with mysql as backends
      env:
        - scenario=deploy-kea-mysql
      script:
        - >
           travis_wait 45 sleep infinity & docker run --rm -it
           --mount type=bind,source="$(pwd)",target=/tmp/$(basename "$PWD")
           -v /var/run/docker.sock:/var/run/docker.sock
           -w /tmp/$(basename "$PWD")
           quay.io/ansible/molecule:latest
           sudo molecule test --scenario-name $scenario

notifications:
  email:
    on_failure: change
    on_success: never
