---
sudo: required
language: python
services:
  - docker

cache: ccache

stages:
  - linter
  - test

env:
  - image=debian version=8 group=memfile
  - image=debian version=8 group=mysql
  - image=debian version=9 group=memfile
  - image=debian version=9 group=mysql
  - image=centos version=7 group=memfile
  - image=centos version=7 group=mysql

matrix:
  fast_finish: true
  allow_failures:
    - env: image=centos version=7 group=memfile
    - env: image=centos version=7 group=mysql

jobs:
  include:
    - stage: linter
      env: image=debian verion=9 group=memfile
      script:
        - >
           docker run --rm -it
           --mount type=bind,source="$(pwd)",target=/tmp/$(basename "$PWD")
           -v /var/run/docker.sock:/var/run/docker.sock
           -w /tmp/$(basename "$PWD")
           quay.io/ansible/molecule:latest
           sudo molecule lint

script:
  - >
     travis_wait 60 sleep infinity & docker run --rm -it
     --mount type=bind,source="$(pwd)",target=/tmp/$(basename "$PWD")
     -v /var/run/docker.sock:/var/run/docker.sock
     -v $HOME/.cache:/root/.ccache:rw
     -w /tmp/$(basename "$PWD")
     quay.io/ansible/molecule:latest
     sudo image=$image version=$version group=$group molecule test

notifications:
  email:
    on_failure: change
    on_success: never
