---
- name: "configure kea build"
  command: "./configure --with-mysql --with-openssl"
  args:
    chdir: "kea-{{ kea_version }}"
  tags:
    - install
  when:
    - kea_database_backends == "memfile"

- name: "configure kea build"
  command: "./configure --with-mysql --with-openssl"
  args:
    chdir: "kea-{{ kea_version }}"
  tags:
    - install
  when: kea_database_backends == "mysql"

- name: "build kea dhcp server"
  command: "make"
  args:
    chdir: "kea-{{ kea_version }}"
  tags:
    - install

- name: "install kea dhcp server"
  command: "make install"
  args:
    chdir: "kea-{{ kea_version }}"
  tags:
    - install

- name: "finish install"
  command: "ldconfig"
  tags:
    - install
