---
- name: "upgrade packages"
  apt:
    update_cache: true
    upgrade: full
  tags:
    - install
    - prerequisites

- name: "install building requirements"
  apt:
    name: "{{ kea_building_requirements }}"
    state: present
    update_cache: true
  tags:
    - install
    - prerequisites
