---
- name: "import database backends variables"
  include_vars: "{{ kea_database_backends }}.yml"
  tags:
    - install
    - backends

- name: "install database backends"
  include_tasks: "debian-{{ kea_database_backends }}-install.yml"
  tags:
    - install
    - backends
