---
- name: "import {{ ansible_os_family | lower }} variables"
  include_vars: "{{ ansible_os_family | lower }}.yml"
  tags:
    - install
    - variables

- name: "install prerequisites software"
  include_tasks: "{{ ansible_os_family | lower }}-prerequisites.yml"
  tags:
    - install
    - prerequisites

- name: "manage kea user"
  include_tasks: "user.yml"
  tags:
    - install
    - user

- name: "install database backends prerequisites"
  include_tasks: "{{ ansible_os_family | lower }}-backends.yml"
  when: kea_database_backends == "mysql" or kea_database_backends == "postgresql" or kea_database_backends == "cassandra"
  tags:
    - install
    - backends
