---
- name: "install epel-release"
  yum:
    name:
      - epel-release
      - centos-release-scl
    state: present
  tags:
    - install
    - prerequisites

- name: "install building requirements"
  yum:
    name: "{{ kea_building_requirements }}"
    state: present
  tags:
    - install
    - prerequisites

- name: "set path to GCC 7"
  command: scl enable devtoolset-7 bash
  tags:
    - install
    - prerequisites
