---
- name: "install repo"
  yum:
    name:
      - epel-release
      - centos-release-scl
    state: present
  tags:
    - install
    - prerequisites

- name: "install building requirements"
  yum:
    name: "{{ kea_building_requirements }}"
    state: present
  tags:
    - install
    - prerequisites
