---
dependency:
  name: galaxy
  options:
    role-files: requirements.yml

driver:
  name: docker

lint: |
  set -e
  yamllint -c ./molecule/resources/rules/yamllint.yaml .
  ansible-lint .
  flake8

platforms:
  - name: "kea-$image$version$group"
    image: "$image:$version"
    volumes:
      - /home/travis/.ccache:/root/.ccache:rw
    env:
      container: docker
      PATH: "/usr/lib64/ccache:$PATH"
      PKG_CONFIG_PATH: "/usr/local/lib64/pkgconfig"
      CXX: "ccache g++"
      CC: "ccache gcc"
    groups:
      - "$group"

provisioner:
  log: true
  name: ansible
  inventory:
    links:
      group_vars: group_vars/
      host_vars: host_vars/
  playbooks:
    converge: ../ressources/playbook.yml
  options:
    vvv: true
    dif: true

scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    # - side_effect
    # - verify

verifier:
  name: testinfra
