---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint
  options:
    config-file: molecule/ressources/rules/yaml-lint.yml

platforms:
  - name: kea-$image-$version-$group
    image: $image:$version
    env:
      container: docker
    groups:
      - $group

provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      force-color: true
  playbooks:
    converge: ../ressources/playbook.yml

scenario:
  name: default
  lint_sequence:
    - lint
    - syntax
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy

verifier:
  name: testinfra
  lint:
    name: flake8
