---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint
  options:
    config-file: molecule/ressources/rules/yaml-lint.yml

platforms:
  - name: "kea-$image$version$group"
    image: "$image:$version"
    volumes:
      - /root/.ccache:/root/.ccache:rw
    env:
      container: docker
    groups:
      - "$group"

provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      force-color: true
  inventory:
    links:
      group_vars: group_vars/
      host_vars: host_vars/
  playbooks:
    converge: ../ressources/playbook.yml
  options:
    vvv: true

scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    # - side_effect
    # - verify
    - destroy

verifier:
  name: testinfra
  lint:
    name: flake8
