---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: kea-debian-7
    image: debian:7
    env:
      container: docker
    groups:
      - deploy
      - mysql
  - name: kea-debian-8
    image: debian:8
    env:
      container: docker
    groups:
      - deploy
      - mysql
  - name: kea-debian-9
    image: debian:9
    env:
      container: docker
    groups:
      - deploy
      - mysql
  - name: kea-centos-7
    image: centos:7
    env:
      container: docker
    groups:
      - deploy
      - mysql

provisioner:
  name: ansible
  inventory:
    links:
      group_vars: group_vars/
      host_vars: host_vars/
  playbooks:
    converge: ../ressources/playbook.yml
  options:
    vvv: true

scenario:
  name: deploy-kea-mysql
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy

verifier:
  name: testinfra
  lint:
    name: flake8
